# Generated by Django 5.1.7 on 2025-04-09 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_principal_admin_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlaBal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.subjects')),
            ],
            options={
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
    ]
