# Generated by Django 5.1.7 on 2025-04-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_blabal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlaBal',
        ),
    ]
