# Generated by Django 5.1.7 on 2025-04-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_delete_blabal'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
